{{- if .Values.secrets.externalSecretContract }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-platform-dependencies
  namespace: agent-platform-control
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Values.secrets.storeRefName }}"
    kind: "{{ .Values.secrets.storeRefKind }}"
  target:
    name: "{{ .Values.secrets.externalSecretName }}"
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: "{{ .Values.secrets.remoteKey }}"
{{- end }}
