"""Portable platform adapters for transport and lossy diagnostics."""
from .config_reader import (
    AppConfig,
    ConfigReader,
    FallbackConfig,
    LoggingConfig,
    ProviderConfig,
    ProviderParameters,
    ProviderType,
    SessionConfig,
)
from .logging_json import (
    JsonLogFormatter,
    correlation,
    install_json_logs,
    set_attempt_id,
    set_run_id,
    set_trace_id,
)
from .message_bus import (
    InboxConsumer,
    InMemoryMessageBus,
    MessageBus,
    MessageDelivery,
    MessageEnvelope,
    NatsJetStreamBus,
)
from .outbox import OutboxPublishBatch, OutboxPublisher
from .provider_factory import (
    ProviderFactory,
    load_provider,
)
from .telemetry import (
    CompositeDiagnosticSink,
    CorrectnessSignal,
    DiagnosticTelemetry,
    InMemoryDiagnosticSink,
    MetricLabelPolicy,
    OpenTelemetryDiagnosticSink,
    PrometheusMetricSink,
    SpanHandle,
    SpanLink,
    TelemetryPolicyError,
    prometheus_text,
)
from .telemetry_service import (
    TelemetrySessionProvider,
    create_telemetry_from_env,
    default_metric_label_policy,
    http_route_bucket,
    http_status_class,
    maybe_wrap_sessions,
    prometheus_enabled,
    prometheus_registry,
)

__all__ = [
    "AppConfig",
    "CompositeDiagnosticSink",
    "ConfigReader",
    "CorrectnessSignal",
    "DiagnosticTelemetry",
    "FallbackConfig",
    "InMemoryDiagnosticSink",
    "InMemoryMessageBus",
    "InboxConsumer",
    "JsonLogFormatter",
    "LoggingConfig",
    "MessageBus",
    "MessageDelivery",
    "MessageEnvelope",
    "MetricLabelPolicy",
    "NatsJetStreamBus",
    "OpenTelemetryDiagnosticSink",
    "OutboxPublishBatch",
    "OutboxPublisher",
    "PrometheusMetricSink",
    "ProviderConfig",
    "ProviderFactory",
    "ProviderParameters",
    "ProviderType",
    "SessionConfig",
    "SpanHandle",
    "SpanLink",
    "TelemetryPolicyError",
    "TelemetrySessionProvider",
    "correlation",
    "create_telemetry_from_env",
    "default_metric_label_policy",
    "http_route_bucket",
    "http_status_class",
    "install_json_logs",
    "load_provider",
    "maybe_wrap_sessions",
    "prometheus_enabled",
    "prometheus_registry",
    "prometheus_text",
    "set_attempt_id",
    "set_run_id",
    "set_trace_id",
]
