#!/usr/bin/env python3
"""Generate deploy/observability/prometheus-rules-classic.yaml from the
PrometheusRule CRD (deploy/observability/prometheus-rules.yaml).

The classic twin is what the gate's Prometheus mounts as ``rule_files``
(ConfigMap key ``prometheus-rules-classic.yaml``). It mirrors the CRD alert
set 1:1 (same alert/expr/for/labels/annotations) and adds the two recording
rules the SLO burn-expressions depend on:

  agent_platform:http_error_ratio_5m / _6h = 5xx share of total HTTP
  observations (from the RED latency histogram — the only HTTP signal the
  platform exports is the latency histogram, whose _counts carry the
  http.status_class label).

Rule count check: the observability gate asserts ``/api/v1/rules`` >= 15.
The classic file yields 14 alerts + 2 recording rules = 16 matching rules
after Prometheus ingests it.
"""
from __future__ import annotations

import sys
from datetime import UTC, datetime

import yaml

CRD_PATH = "deploy/observability/prometheus-rules.yaml"
OUT_PATH = "deploy/observability/prometheus-rules-classic.yaml"

LAT_METRIC = "agent_platform_http_latency_seconds"


def main() -> int:
    with open(CRD_PATH, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    if doc.get("kind") != "PrometheusRule":
        print(f"{CRD_PATH}: not a PrometheusRule", file=sys.stderr)
        return 3

    groups = []
    for grp in doc["spec"]["groups"]:
        rules = []
        for rule in grp.get("rules", []):
            # classic file uses group-level interval; keep per-rule fields intact
            entry = {"alert": rule["alert"],
                     "expr": rule["expr"],
                     "for": rule.get("for", "0m")}
            if rule.get("labels"):
                entry["labels"] = rule["labels"]
            if rule.get("annotations"):
                entry["annotations"] = rule["annotations"]
            rules.append(entry)
        groups.append({
            "name": grp["name"],
            "interval": grp.get("interval", "15s"),
            "rules": rules,
        })

    # recording rules the SLO burn exprs reference (error share of HTTP RED)
    groups.append({
        "name": "agent-platform.recording",
        "interval": "30s",
        "rules": [
            {
                "record": "agent_platform:http_error_ratio_5m",
                "expr": (
                    f'sum(rate({LAT_METRIC}_count{{http_status_class="5xx"}}[5m]))'
                    f' / clamp_min(sum(rate({LAT_METRIC}_count[5m])), 1.0)'
                ),
            },
            {
                "record": "agent_platform:http_error_ratio_6h",
                "expr": (
                    f'sum(rate({LAT_METRIC}_count{{http_status_class="5xx"}}[6h]))'
                    f' / clamp_min(sum(rate({LAT_METRIC}_count[6h])), 1.0)'
                ),
            },
        ],
    })

    payload = {
        "groups": groups,
    }
    n_alerts = sum(len(g["rules"]) for g in groups if "alert" in g["rules"][0] if g["rules"])
    n_total = sum(len(g["rules"]) for g in groups)

    header = (
        "# Prometheus rule_files (classic) — 1:1 twin of the PrometheusRule CRD\n"
        "# (deploy/observability/prometheus-rules.yaml), mounted by the gate's\n"
        "# Prometheus via ConfigMap key \"prometheus-rules-classic.yaml\".\n"
        "# Alerts: identical to the CRD. Recording rules: the two SLO burn-ratio\n"
        "# inputs the CRD's availability alerts reference (5xx share of HTTP RED).\n"
        "# Generated by scripts/gen-rule-classic.py at %s (UTC).\n"
        % datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")
    )
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header)
        yaml.safe_dump(payload, fh, sort_keys=False, default_flow_style=False)

    print(f"wrote {OUT_PATH}: {n_total} rules ({n_alerts} alerts + {n_total - n_alerts} recording)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())