"""Async persistence ports shared by memory and PostgreSQL adapters."""
from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol, runtime_checkable

from enterprise_agent_platform.contracts.events import EnterpriseEventEnvelope
from enterprise_agent_platform.domain.records import (
    ActionProposalRecord,
    ApprovalRequestRecord,
    ArtifactRecord,
    ArtifactVersionRecord,
    AttemptRecord,
    AuditEventRecord,
    CheckpointRecord,
    EffectLedgerRecord,
    ExecutionLeaseRecord,
    ExecutionUnitRecord,
    IdempotencyRecord,
    InboxMessageRecord,
    OutboxMessageRecord,
    RunAuthorizationSnapshotRecord,
    RunRecord,
    SchedulableWork,
    StepRecord,
    UiSurfaceRecord,
    UiSurfaceRevisionRecord,
    WorkspaceSnapshotRecord,
)


class PlatformError(RuntimeError):
    """Stable machine-readable domain/persistence error."""

    def __init__(self, code: str, message: str, *, retryable: bool = False) -> None:
        self.code = code
        self.message = message
        self.retryable = retryable
        super().__init__(f"{code}: {message}")


@runtime_checkable
class PlatformTransaction(Protocol):
    async def db_now(self) -> datetime: ...
    async def lock_run(self, tenant_id: str, run_id: str) -> RunRecord: ...
    async def lock_execution_unit(
        self, tenant_id: str, execution_unit_id: str
    ) -> ExecutionUnitRecord: ...
    async def get_run(self, tenant_id: str, run_id: str) -> RunRecord: ...
    async def get_run_authorization_snapshot(
        self, tenant_id: str, run_id: str
    ) -> RunAuthorizationSnapshotRecord: ...
    async def get_primary_unit(self, tenant_id: str, run_id: str) -> ExecutionUnitRecord: ...
    async def get_execution_unit(
        self, tenant_id: str, execution_unit_id: str
    ) -> ExecutionUnitRecord: ...
    async def get_checkpoint(self, tenant_id: str, checkpoint_id: str) -> CheckpointRecord: ...
    async def get_step(self, tenant_id: str, step_id: str) -> StepRecord: ...
    async def get_attempt(self, tenant_id: str, attempt_id: str) -> AttemptRecord: ...
    async def get_lease_for_attempt(
        self, tenant_id: str, attempt_id: str
    ) -> ExecutionLeaseRecord: ...
    async def get_workspace_snapshot(
        self, tenant_id: str, snapshot_id: str
    ) -> WorkspaceSnapshotRecord: ...
    async def get_artifact_version(
        self, tenant_id: str, artifact_id: str, version: int
    ) -> ArtifactVersionRecord: ...
    async def get_ui_surface(self, tenant_id: str, surface_id: str) -> UiSurfaceRecord | None: ...
    async def get_ui_surface_revision(
        self, tenant_id: str, surface_id: str, revision: int
    ) -> UiSurfaceRevisionRecord: ...
    async def get_action_proposal(
        self, tenant_id: str, action_ref: str
    ) -> ActionProposalRecord: ...
    async def get_approval_request(
        self, tenant_id: str, approval_id: str
    ) -> ApprovalRequestRecord: ...
    async def get_effect(self, tenant_id: str, effect_id: str) -> EffectLedgerRecord: ...
    async def get_effect_by_key(
        self, tenant_id: str, effect_key: str
    ) -> EffectLedgerRecord | None: ...
    async def get_inbox_message(
        self, tenant_id: str, message_id: str, handler_version: str
    ) -> InboxMessageRecord: ...
    async def list_execution_units_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[ExecutionUnitRecord, ...]: ...
    async def list_active_attempts_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[AttemptRecord, ...]: ...
    async def list_attempts_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[AttemptRecord, ...]: ...
    async def list_active_leases_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[ExecutionLeaseRecord, ...]: ...
    async def list_events_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[EnterpriseEventEnvelope, ...]: ...
    async def list_ui_surfaces_for_run(
        self, tenant_id: str, run_id: str
    ) -> tuple[UiSurfaceRecord, ...]: ...
    async def get_event_retention_floor(self, tenant_id: str, run_id: str) -> int: ...
    async def list_schedulable_work(self) -> tuple[SchedulableWork, ...]: ...
    async def claim_idempotency(
        self,
        tenant_id: str,
        namespace: str,
        idempotency_key: str,
        request_digest: str,
        actor_id: str,
        now: datetime,
    ) -> IdempotencyRecord | None: ...
    async def complete_idempotency(
        self,
        tenant_id: str,
        namespace: str,
        idempotency_key: str,
        request_digest: str,
        result_type: str,
        result_id: str,
        result_schema: str,
        result_payload: dict[str, object],
        now: datetime,
    ) -> IdempotencyRecord: ...
    async def insert_run(self, record: RunRecord) -> None: ...
    async def insert_run_authorization_snapshot(
        self, record: RunAuthorizationSnapshotRecord
    ) -> None: ...
    async def insert_execution_unit(self, record: ExecutionUnitRecord) -> None: ...
    async def insert_checkpoint(self, record: CheckpointRecord) -> None: ...
    async def insert_step(self, record: StepRecord) -> None: ...
    async def insert_attempt(self, record: AttemptRecord) -> None: ...
    async def insert_lease(self, record: ExecutionLeaseRecord) -> None: ...
    async def insert_workspace_snapshot(self, record: WorkspaceSnapshotRecord) -> None: ...
    async def insert_artifact(self, record: ArtifactRecord) -> None: ...
    async def insert_artifact_version(self, record: ArtifactVersionRecord) -> None: ...
    async def insert_ui_surface(self, record: UiSurfaceRecord) -> None: ...
    async def insert_ui_surface_revision(self, record: UiSurfaceRevisionRecord) -> None: ...
    async def insert_action_proposal(self, record: ActionProposalRecord) -> None: ...
    async def insert_approval_request(self, record: ApprovalRequestRecord) -> None: ...
    async def insert_effect(self, record: EffectLedgerRecord) -> None: ...
    async def claim_inbox_message(self, record: InboxMessageRecord) -> bool: ...
    async def replace_run_cas(self, record: RunRecord, expected_version: int) -> None: ...
    async def replace_execution_unit_cas(
        self, record: ExecutionUnitRecord, expected_version: int
    ) -> None: ...
    async def replace_checkpoint_cas(
        self, record: CheckpointRecord, expected_version: int
    ) -> None: ...
    async def replace_attempt_cas(self, record: AttemptRecord, expected_version: int) -> None: ...
    async def replace_lease_cas(
        self, record: ExecutionLeaseRecord, expected_version: int
    ) -> None: ...
    async def replace_inbox_message_cas(
        self, record: InboxMessageRecord, expected_version: int
    ) -> None: ...
    async def replace_action_proposal_cas(
        self, record: ActionProposalRecord, expected_version: int
    ) -> None: ...
    async def replace_approval_request_cas(
        self, record: ApprovalRequestRecord, expected_version: int
    ) -> None: ...
    async def replace_effect_cas(
        self, record: EffectLedgerRecord, expected_version: int
    ) -> None: ...
    async def replace_outbox_cas(
        self, record: OutboxMessageRecord, expected_version: int
    ) -> None: ...
    async def replace_ui_surface_cas(
        self, record: UiSurfaceRecord, expected_version: int
    ) -> None: ...
    async def append_event(
        self, event: EnterpriseEventEnvelope, expected_previous_seq: int
    ) -> None: ...
    async def insert_outbox(self, record: OutboxMessageRecord) -> None: ...
    async def insert_audit(self, record: AuditEventRecord) -> None: ...


@runtime_checkable
class PlatformStore(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[PlatformTransaction]: ...
    def new_id(self, kind: str) -> str: ...
    async def get_run(self, tenant_id: str, run_id: str) -> RunRecord: ...
    async def get_run_authorization_snapshot(
        self, tenant_id: str, run_id: str
    ) -> RunAuthorizationSnapshotRecord: ...
    async def get_primary_unit(self, tenant_id: str, run_id: str) -> ExecutionUnitRecord: ...
    async def get_execution_unit(
        self, tenant_id: str, execution_unit_id: str
    ) -> ExecutionUnitRecord: ...
    async def get_checkpoint(self, tenant_id: str, checkpoint_id: str) -> CheckpointRecord: ...
    async def get_step(self, tenant_id: str, step_id: str) -> StepRecord: ...
    async def get_attempt(self, tenant_id: str, attempt_id: str) -> AttemptRecord: ...
    async def get_lease_for_attempt(
        self, tenant_id: str, attempt_id: str
    ) -> ExecutionLeaseRecord: ...
    async def get_workspace_snapshot(
        self, tenant_id: str, snapshot_id: str
    ) -> WorkspaceSnapshotRecord: ...
    async def get_artifact_version(
        self, tenant_id: str, artifact_id: str, version: int
    ) -> ArtifactVersionRecord: ...
    async def get_ui_surface(self, tenant_id: str, surface_id: str) -> UiSurfaceRecord | None: ...
    async def get_ui_surface_revision(
        self, tenant_id: str, surface_id: str, revision: int
    ) -> UiSurfaceRevisionRecord: ...
    async def get_action_proposal(
        self, tenant_id: str, action_ref: str
    ) -> ActionProposalRecord: ...
    async def get_approval_request(
        self, tenant_id: str, approval_id: str
    ) -> ApprovalRequestRecord: ...
    async def get_effect(self, tenant_id: str, effect_id: str) -> EffectLedgerRecord: ...
    async def get_effect_by_key(
        self, tenant_id: str, effect_key: str
    ) -> EffectLedgerRecord | None: ...
    async def get_outbox_message(
        self, tenant_id: str, message_id: str
    ) -> OutboxMessageRecord: ...
    async def get_inbox_message(
        self, tenant_id: str, message_id: str, handler_version: str
    ) -> InboxMessageRecord: ...
    async def list_schedulable_work(self) -> tuple[SchedulableWork, ...]: ...
    async def list_ui_surfaces(
        self, tenant_id: str, run_id: str | None = None
    ) -> tuple[UiSurfaceRecord, ...]: ...
    async def list_events(
        self, tenant_id: str, run_id: str
    ) -> tuple[EnterpriseEventEnvelope, ...]: ...
    async def list_outbox(
        self, tenant_id: str, run_id: str | None = None
    ) -> tuple[OutboxMessageRecord, ...]: ...
    async def list_pending_outbox(self, *, limit: int = 100) -> tuple[OutboxMessageRecord, ...]: ...
    async def list_audit_events(
        self, tenant_id: str, run_id: str | None = None
    ) -> tuple[AuditEventRecord, ...]: ...
    async def list_approval_requests(
        self, tenant_id: str, run_id: str
    ) -> tuple[ApprovalRequestRecord, ...]: ...
    async def list_effects(
        self, tenant_id: str, run_id: str | None = None
    ) -> tuple[EffectLedgerRecord, ...]: ...
