"""Complete tenant-qualified SQLAlchemy Core metadata for the V1 platform."""
from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKeyConstraint,
    Index,
    Integer,
    MetaData,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

from enterprise_agent_platform.contracts.enums import (
    ActionProposalState,
    ApprovalState,
    ArtifactVersionState,
    AttemptState,
    CheckpointState,
    EffectState,
    ExecutionLeaseState,
    ExecutionUnitState,
    RunState,
    ToolGrantState,
    ToolInvocationState,
    WorkspaceSnapshotState,
)

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    # Check constraints are explicitly named at definition time. Preserve those
    # stable names verbatim instead of prefixing them a second time.
    "ck": "%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

JSON_DOCUMENT = JSON(none_as_null=True).with_variant(JSONB(none_as_null=True), "postgresql")
TIMESTAMP = DateTime(timezone=True)
ID = String(255)
STATE = String(64)


def _tenant() -> Column[str]:
    return Column("tenant_id", ID, nullable=False)


def _enum_check(table: str, column: str, values: list[str]) -> CheckConstraint:
    rendered = ", ".join(f"'{value}'" for value in values)
    return CheckConstraint(
        f"{column} IN ({rendered})",
        name=f"ck_{table}_{column}",
    )


def _version_check(table: str) -> CheckConstraint:
    return CheckConstraint("version >= 1", name=f"ck_{table}_version")


def _fk(
    local: list[str],
    remote: list[str],
    *,
    name: str,
    use_alter: bool = False,
    deferrable: bool | None = None,
    initially: str | None = None,
) -> ForeignKeyConstraint:
    return ForeignKeyConstraint(
        local,
        remote,
        name=name,
        ondelete="RESTRICT",
        use_alter=use_alter,
        deferrable=deferrable,
        initially=initially,
    )


run_table = Table(
    "run",
    metadata,
    _tenant(),
    Column("run_id", ID, nullable=False),
    Column("owner_id", ID, nullable=False),
    Column("parent_run_id", ID),
    Column("workflow_type", String(128), nullable=False),
    Column("intent", Text, nullable=False),
    Column("resource_refs", JSON_DOCUMENT, nullable=False),
    Column("parameters", JSON_DOCUMENT, nullable=False),
    Column("host_context_ref", String(512)),
    Column("status", STATE, nullable=False),
    Column("status_reason", String(255)),
    Column("version", Integer, nullable=False),
    Column("last_event_seq", BigInteger, nullable=False),
    Column("fsm_version", String(64), nullable=False),
    Column("cancel_requested_by", ID),
    Column("cancel_requested_at", TIMESTAMP),
    Column("cancel_reason", Text),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    Column("ended_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "run_id", name="pk_run"),
    _fk(
        ["tenant_id", "parent_run_id"],
        ["run.tenant_id", "run.run_id"],
        name="fk_run_tenant_parent",
        use_alter=True,
    ),
    _enum_check("run", "status", [item.value for item in RunState]),
    _version_check("run"),
    CheckConstraint("last_event_seq >= 0", name="ck_run_last_event_seq"),
    CheckConstraint(
        "(cancel_requested_by IS NULL AND cancel_requested_at IS NULL) OR "
        "(cancel_requested_by IS NOT NULL AND cancel_requested_at IS NOT NULL)",
        name="ck_run_cancel_request_shape",
    ),
    Index(
        "ix_run_tenant_status_created",
        "tenant_id",
        "status",
        "created_at",
    ),
)

run_authorization_snapshot_table = Table(
    "run_authorization_snapshot",
    metadata,
    _tenant(),
    Column("run_id", ID, nullable=False),
    Column("resolved_resources", JSON_DOCUMENT, nullable=False),
    Column("host_context_digest", String(128)),
    Column("host_context_version", String(64)),
    Column("policy_digest", String(128), nullable=False),
    Column("policy_version", String(64), nullable=False),
    Column("policy_scopes", JSON_DOCUMENT, nullable=False),
    Column("policy_budget", JSON_DOCUMENT, nullable=False),
    Column("snapshot_digest", String(128), nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "run_id", name="pk_run_authorization_snapshot"),
    _fk(
        ["tenant_id", "run_id"],
        ["run.tenant_id", "run.run_id"],
        name="fk_run_authorization_snapshot_tenant_run",
    ),
    CheckConstraint(
        "(host_context_digest IS NULL AND host_context_version IS NULL) OR "
        "(host_context_digest IS NOT NULL AND host_context_version IS NOT NULL)",
        name="ck_run_authorization_snapshot_host_context_pair",
    ),
)

step_table = Table(
    "step",
    metadata,
    _tenant(),
    Column("step_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("ordinal", Integer, nullable=False),
    Column("name", String(255), nullable=False),
    Column("step_type", String(128), nullable=False),
    Column("policy_snapshot", JSON_DOCUMENT, nullable=False),
    Column("status", STATE, nullable=False),
    Column("status_reason", String(255)),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    Column("ended_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "step_id", name="pk_step"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_step_tenant_run"),
    UniqueConstraint("tenant_id", "run_id", "ordinal", name="uq_step_tenant_run_ordinal"),
    UniqueConstraint("tenant_id", "step_id", "run_id", name="uq_step_tenant_step_run"),
    _version_check("step"),
    CheckConstraint("ordinal >= 0", name="ck_step_ordinal"),
)

execution_unit_table = Table(
    "execution_unit",
    metadata,
    _tenant(),
    Column("execution_unit_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("role", String(128), nullable=False),
    Column("status", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("current_checkpoint_id", ID),
    Column("next_generation", BigInteger, nullable=False),
    Column("runtime_profile", String(128), nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "execution_unit_id", name="pk_execution_unit"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_execution_unit_tenant_run"),
    _fk(
        ["tenant_id", "current_checkpoint_id", "execution_unit_id", "run_id"],
        [
            "checkpoint.tenant_id",
            "checkpoint.checkpoint_id",
            "checkpoint.execution_unit_id",
            "checkpoint.run_id",
        ],
        name="fk_execution_unit_tenant_current_checkpoint",
        use_alter=True,
        deferrable=True,
        initially="DEFERRED",
    ),
    UniqueConstraint("tenant_id", "run_id", "role", name="uq_execution_unit_tenant_run_role"),
    UniqueConstraint(
        "tenant_id",
        "execution_unit_id",
        "run_id",
        name="uq_execution_unit_tenant_unit_run",
    ),
    _enum_check("execution_unit", "status", [item.value for item in ExecutionUnitState]),
    _version_check("execution_unit"),
    CheckConstraint("next_generation >= 0", name="ck_execution_unit_next_generation"),
    Index(
        "ix_execution_unit_tenant_run_status",
        "tenant_id",
        "run_id",
        "status",
    ),
)

checkpoint_table = Table(
    "checkpoint",
    metadata,
    _tenant(),
    Column("checkpoint_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("source_attempt_id", ID),
    Column("checkpoint_seq", BigInteger, nullable=False),
    Column("state", STATE, nullable=False),
    Column("workflow_cursor", JSON_DOCUMENT, nullable=False),
    Column("completed_step_ids", JSON_DOCUMENT, nullable=False, server_default=text("'[]'")),
    Column("active_step_context", JSON_DOCUMENT, nullable=False, server_default=text("'{}'")),
    Column("last_event_seq", BigInteger, nullable=False),
    Column("input_artifact_versions", JSON_DOCUMENT, nullable=False, server_default=text("'[]'")),
    Column("output_artifact_versions", JSON_DOCUMENT, nullable=False, server_default=text("'[]'")),
    Column("workspace_snapshot_id", ID),
    Column("resolved_tool_call_ids", JSON_DOCUMENT, nullable=False, server_default=text("'[]'")),
    Column("effect_states", JSON_DOCUMENT, nullable=False, server_default=text("'{}'")),
    Column("budget_consumed", JSON_DOCUMENT, nullable=False, server_default=text("'{}'")),
    Column("model_context_summary_ref", String(512)),
    Column("runtime_image_digest", String(255)),
    Column("agent_state", JSON_DOCUMENT, nullable=False, server_default=text("'{}'")),
    Column(
        "agent_state_schema_version",
        String(64),
        nullable=False,
        server_default=text("'pi-agent-core/v1'"),
    ),
    Column("checkpoint_schema_version", String(64), nullable=False),
    Column("runtime_profile_version", String(128), nullable=False),
    Column("policy_version", String(64), nullable=False),
    Column("tool_catalog_version", String(64), nullable=False),
    Column("ui_catalog_version", String(64), nullable=False),
    Column("checksum", String(128), nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("committed_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "checkpoint_id", name="pk_checkpoint"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_checkpoint_tenant_run"),
    _fk(
        ["tenant_id", "execution_unit_id", "run_id"],
        ["execution_unit.tenant_id", "execution_unit.execution_unit_id", "execution_unit.run_id"],
        name="fk_checkpoint_tenant_unit_run",
    ),
    _fk(
        ["tenant_id", "source_attempt_id", "execution_unit_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.execution_unit_id", "attempt.run_id"],
        name="fk_checkpoint_tenant_source_attempt_unit_run",
        use_alter=True,
    ),
    _fk(
        ["tenant_id", "workspace_snapshot_id", "execution_unit_id", "run_id"],
        [
            "workspace_snapshot.tenant_id",
            "workspace_snapshot.snapshot_id",
            "workspace_snapshot.execution_unit_id",
            "workspace_snapshot.run_id",
        ],
        name="fk_checkpoint_tenant_workspace_snapshot_unit_run",
        use_alter=True,
    ),
    UniqueConstraint("tenant_id", "execution_unit_id", "checkpoint_seq", name="uq_checkpoint_tenant_unit_seq"),
    UniqueConstraint("tenant_id", "checkpoint_id", "execution_unit_id", name="uq_checkpoint_tenant_checkpoint_unit"),
    UniqueConstraint(
        "tenant_id",
        "checkpoint_id",
        "execution_unit_id",
        "run_id",
        name="uq_checkpoint_tenant_checkpoint_unit_run",
    ),
    _enum_check("checkpoint", "state", [item.value for item in CheckpointState]),
    _version_check("checkpoint"),
    CheckConstraint("checkpoint_seq >= 0", name="ck_checkpoint_seq"),
    CheckConstraint("last_event_seq >= 0", name="ck_checkpoint_last_event_seq"),
    CheckConstraint(
        "(state = 'COMMITTED' AND committed_at IS NOT NULL) OR "
        "(state <> 'COMMITTED' AND committed_at IS NULL)",
        name="ck_checkpoint_commit_shape",
    ),
)

attempt_table = Table(
    "attempt",
    metadata,
    _tenant(),
    Column("attempt_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("step_id", ID),
    Column("generation", BigInteger, nullable=False),
    Column("status", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("runtime_profile", String(128), nullable=False),
    Column("source_checkpoint_id", ID),
    Column("reservation_key", String(255), nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    Column("started_at", TIMESTAMP),
    Column("ended_at", TIMESTAMP),
    Column("failure_id", ID),
    PrimaryKeyConstraint("tenant_id", "attempt_id", name="pk_attempt"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_attempt_tenant_run"),
    _fk(
        ["tenant_id", "execution_unit_id", "run_id"],
        ["execution_unit.tenant_id", "execution_unit.execution_unit_id", "execution_unit.run_id"],
        name="fk_attempt_tenant_unit_run",
    ),
    _fk(
        ["tenant_id", "step_id", "run_id"],
        ["step.tenant_id", "step.step_id", "step.run_id"],
        name="fk_attempt_tenant_step_run",
    ),
    _fk(
        ["tenant_id", "source_checkpoint_id", "execution_unit_id", "run_id"],
        [
            "checkpoint.tenant_id",
            "checkpoint.checkpoint_id",
            "checkpoint.execution_unit_id",
            "checkpoint.run_id",
        ],
        name="fk_attempt_tenant_source_checkpoint_unit_run",
    ),
    _fk(
        ["tenant_id", "failure_id"],
        ["execution_error.tenant_id", "execution_error.error_id"],
        name="fk_attempt_tenant_failure",
        use_alter=True,
    ),
    UniqueConstraint("tenant_id", "execution_unit_id", "generation", name="uq_attempt_tenant_unit_generation"),
    UniqueConstraint(
        "tenant_id",
        "attempt_id",
        "execution_unit_id",
        "generation",
        name="uq_attempt_tenant_attempt_unit_generation",
    ),
    UniqueConstraint("tenant_id", "attempt_id", "execution_unit_id", name="uq_attempt_tenant_attempt_unit"),
    UniqueConstraint("tenant_id", "attempt_id", "execution_unit_id", "run_id", name="uq_attempt_tenant_attempt_unit_run"),
    UniqueConstraint("tenant_id", "attempt_id", "run_id", name="uq_attempt_tenant_attempt_run"),
    UniqueConstraint(
        "tenant_id",
        "attempt_id",
        "generation",
        "run_id",
        name="uq_attempt_tenant_attempt_generation_run",
    ),
    UniqueConstraint(
        "tenant_id",
        "attempt_id",
        "execution_unit_id",
        "generation",
        "run_id",
        name="uq_attempt_tenant_attempt_unit_generation_run",
    ),
    _enum_check("attempt", "status", [item.value for item in AttemptState]),
    _version_check("attempt"),
    CheckConstraint("generation >= 1", name="ck_attempt_generation"),
)

_attempt_active_sql = "status IN ('CREATED', 'PROVISIONING', 'CLAIMED', 'RUNNING', 'CHECKPOINTING')"
Index(
    "uq_attempt_tenant_unit_active",
    attempt_table.c.tenant_id,
    attempt_table.c.execution_unit_id,
    unique=True,
    postgresql_where=text(_attempt_active_sql),
    sqlite_where=text(_attempt_active_sql),
)

attempt_step_table = Table(
    "attempt_step",
    metadata,
    _tenant(),
    Column("attempt_id", ID, nullable=False),
    Column("step_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("ordinal", Integer, nullable=False),
    Column("entered_at", TIMESTAMP, nullable=False),
    Column("ended_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "attempt_id", "step_id", name="pk_attempt_step"),
    _fk(
        ["tenant_id", "attempt_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.run_id"],
        name="fk_attempt_step_tenant_attempt_run",
    ),
    _fk(
        ["tenant_id", "step_id", "run_id"],
        ["step.tenant_id", "step.step_id", "step.run_id"],
        name="fk_attempt_step_tenant_step_run",
    ),
    CheckConstraint("ordinal >= 0", name="ck_attempt_step_ordinal"),
)

execution_lease_table = Table(
    "execution_lease",
    metadata,
    _tenant(),
    Column("lease_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("attempt_id", ID, nullable=False),
    Column("generation", BigInteger, nullable=False),
    Column("state", STATE, nullable=False),
    Column("lease_owner", ID),
    Column("version", Integer, nullable=False),
    Column("activated_from_version", Integer),
    Column("provision_deadline", TIMESTAMP, nullable=False),
    Column("heartbeat_at", TIMESTAMP),
    Column("lease_expires_at", TIMESTAMP),
    Column("released_at", TIMESTAMP),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "lease_id", name="pk_execution_lease"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_execution_lease_tenant_run"),
    _fk(
        ["tenant_id", "execution_unit_id"],
        ["execution_unit.tenant_id", "execution_unit.execution_unit_id"],
        name="fk_execution_lease_tenant_unit",
    ),
    _fk(
        ["tenant_id", "attempt_id", "execution_unit_id", "generation"],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.execution_unit_id",
            "attempt.generation",
        ],
        name="fk_execution_lease_tenant_attempt_unit_generation",
    ),
    _fk(
        ["tenant_id", "attempt_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.run_id"],
        name="fk_execution_lease_tenant_attempt_run",
    ),
    UniqueConstraint("tenant_id", "attempt_id", name="uq_execution_lease_tenant_attempt"),
    _enum_check("execution_lease", "state", [item.value for item in ExecutionLeaseState]),
    _version_check("execution_lease"),
    CheckConstraint("generation >= 1", name="ck_execution_lease_generation"),
    CheckConstraint(
        "activated_from_version IS NULL OR activated_from_version > 0",
        name="ck_execution_lease_activated_from_version",
    ),
    CheckConstraint(
        "(state = 'RESERVED' AND lease_owner IS NULL "
        "AND activated_from_version IS NULL AND heartbeat_at IS NULL "
        "AND lease_expires_at IS NULL) OR "
        "(state = 'ACTIVE' AND lease_owner IS NOT NULL "
        "AND activated_from_version IS NOT NULL AND heartbeat_at IS NOT NULL "
        "AND lease_expires_at IS NOT NULL) OR "
        "(state IN ('RELEASED', 'EXPIRED', 'REVOKED'))",
        name="ck_execution_lease_active_shape",
    ),
)

_lease_active_sql = "state IN ('RESERVED', 'ACTIVE')"
Index(
    "uq_execution_lease_tenant_unit_active",
    execution_lease_table.c.tenant_id,
    execution_lease_table.c.execution_unit_id,
    unique=True,
    postgresql_where=text(_lease_active_sql),
    sqlite_where=text(_lease_active_sql),
)

workspace_snapshot_table = Table(
    "workspace_snapshot",
    metadata,
    _tenant(),
    Column("snapshot_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("source_attempt_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("generation", BigInteger, nullable=False),
    Column("state", STATE, nullable=False),
    Column("manifest_uri", String(1024), nullable=False),
    Column("checksum", String(128), nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("runtime_image_digest", String(255), nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("ready_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "snapshot_id", name="pk_workspace_snapshot"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_workspace_snapshot_tenant_run"),
    _fk(
        [
            "tenant_id",
            "source_attempt_id",
            "execution_unit_id",
            "generation",
            "run_id",
        ],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.execution_unit_id",
            "attempt.generation",
            "attempt.run_id",
        ],
        name="fk_workspace_snapshot_tenant_attempt_unit_generation",
    ),
    UniqueConstraint(
        "tenant_id",
        "source_attempt_id",
        "generation",
        name="uq_workspace_snapshot_tenant_attempt_generation",
    ),
    UniqueConstraint(
        "tenant_id",
        "snapshot_id",
        "execution_unit_id",
        "run_id",
        name="uq_workspace_snapshot_tenant_snapshot_unit_run",
    ),
    _enum_check("workspace_snapshot", "state", [item.value for item in WorkspaceSnapshotState]),
    _version_check("workspace_snapshot"),
    CheckConstraint("size_bytes >= 0", name="ck_workspace_snapshot_size_bytes"),
)

artifact_table = Table(
    "artifact",
    metadata,
    _tenant(),
    Column("artifact_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("logical_name", String(255), nullable=False),
    Column("artifact_type", String(128), nullable=False),
    Column("classification", String(64), nullable=False),
    Column("retention_policy", JSON_DOCUMENT, nullable=False),
    Column("state", STATE, nullable=False),
    Column("current_version", Integer),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "artifact_id", name="pk_artifact"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_artifact_tenant_run"),
    _fk(
        ["tenant_id", "artifact_id", "current_version"],
        ["artifact_version.tenant_id", "artifact_version.artifact_id", "artifact_version.version"],
        name="fk_artifact_tenant_current_version",
        use_alter=True,
        deferrable=True,
        initially="DEFERRED",
    ),
    _enum_check("artifact", "state", ["ACTIVE", "DELETED"]),
    _version_check("artifact"),
    UniqueConstraint("tenant_id", "artifact_id", "run_id", name="uq_artifact_tenant_artifact_run"),
)

artifact_version_table = Table(
    "artifact_version",
    metadata,
    _tenant(),
    Column("artifact_id", ID, nullable=False),
    Column("version", Integer, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("source_attempt_id", ID),
    Column("generation", BigInteger),
    Column("state", STATE, nullable=False),
    Column("state_version", Integer, nullable=False),
    Column("object_uri", String(1024), nullable=False),
    Column("checksum", String(128), nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("media_type", String(255), nullable=False),
    Column("lineage", JSON_DOCUMENT, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("ready_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "artifact_id", "version", name="pk_artifact_version"),
    _fk(
        ["tenant_id", "artifact_id", "run_id"],
        ["artifact.tenant_id", "artifact.artifact_id", "artifact.run_id"],
        name="fk_artifact_version_tenant_artifact_run",
    ),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_artifact_version_tenant_run"),
    _fk(
        ["tenant_id", "source_attempt_id", "generation", "run_id"],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.generation",
            "attempt.run_id",
        ],
        name="fk_artifact_version_tenant_attempt_generation_run",
    ),
    _enum_check("artifact_version", "state", [item.value for item in ArtifactVersionState]),
    _version_check("artifact_version"),
    CheckConstraint("state_version >= 1", name="ck_artifact_version_state_version"),
    CheckConstraint("size_bytes >= 0", name="ck_artifact_version_size_bytes"),
    CheckConstraint(
        "(source_attempt_id IS NULL AND generation IS NULL) OR "
        "(source_attempt_id IS NOT NULL AND generation IS NOT NULL)",
        name="ck_artifact_version_source_attempt_generation_pair",
    ),
)

tool_grant_table = Table(
    "tool_grant",
    metadata,
    _tenant(),
    Column("grant_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("tool_name", String(255), nullable=False),
    Column("tool_spec_version", String(64), nullable=False),
    Column("resource_selectors", JSON_DOCUMENT, nullable=False),
    Column("scopes", JSON_DOCUMENT, nullable=False),
    Column("policy_version", String(64), nullable=False),
    Column("state", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    Column("expires_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "grant_id", name="pk_tool_grant"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_tool_grant_tenant_run"),
    _fk(
        ["tenant_id", "execution_unit_id", "run_id"],
        ["execution_unit.tenant_id", "execution_unit.execution_unit_id", "execution_unit.run_id"],
        name="fk_tool_grant_tenant_unit_run",
    ),
    UniqueConstraint(
        "tenant_id",
        "grant_id",
        "run_id",
        "execution_unit_id",
        "tool_name",
        "tool_spec_version",
        name="uq_tool_grant_tenant_grant_scope",
    ),
    UniqueConstraint("tenant_id", "grant_id", "run_id", name="uq_tool_grant_tenant_grant_run"),
    _enum_check("tool_grant", "state", [item.value for item in ToolGrantState]),
    _version_check("tool_grant"),
)

tool_invocation_table = Table(
    "tool_invocation",
    metadata,
    _tenant(),
    Column("attempt_id", ID, nullable=False),
    Column("call_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("generation", BigInteger, nullable=False),
    Column("tool_name", String(255), nullable=False),
    Column("tool_spec_version", String(64), nullable=False),
    Column("grant_id", ID, nullable=False),
    Column("input_digest", String(128), nullable=False),
    Column("status", STATE, nullable=False),
    Column("risk_class", String(32), nullable=False),
    Column("resource_ref", String(512), nullable=False),
    Column("result_ref", String(512)),
    Column("policy_version", String(64), nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("started_at", TIMESTAMP),
    Column("ended_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "attempt_id", "call_id", name="pk_tool_invocation"),
    _fk(
        [
            "tenant_id",
            "attempt_id",
            "execution_unit_id",
            "generation",
            "run_id",
        ],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.execution_unit_id",
            "attempt.generation",
            "attempt.run_id",
        ],
        name="fk_tool_invocation_tenant_attempt_unit_generation",
    ),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_tool_invocation_tenant_run"),
    _fk(
        [
            "tenant_id",
            "grant_id",
            "run_id",
            "execution_unit_id",
            "tool_name",
            "tool_spec_version",
        ],
        [
            "tool_grant.tenant_id",
            "tool_grant.grant_id",
            "tool_grant.run_id",
            "tool_grant.execution_unit_id",
            "tool_grant.tool_name",
            "tool_grant.tool_spec_version",
        ],
        name="fk_tool_invocation_tenant_grant_scope",
    ),
    _enum_check("tool_invocation", "status", [item.value for item in ToolInvocationState]),
    _version_check("tool_invocation"),
)

action_proposal_table = Table(
    "action_proposal",
    metadata,
    _tenant(),
    Column("action_ref", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("step_id", ID),
    Column("attempt_id", ID, nullable=False),
    Column("execution_unit_id", ID, nullable=False),
    Column("source_generation", BigInteger, nullable=False),
    Column("tool_name", String(255), nullable=False),
    Column("tool_spec_version", String(64), nullable=False),
    Column("tool_spec_digest", String(128), nullable=False),
    Column("connector_name", String(255), nullable=False),
    Column("required_scopes", JSON_DOCUMENT, nullable=False),
    Column("request_digest", String(128), nullable=False),
    Column("canonical_payload_digest", String(128), nullable=False),
    Column("canonical_target", String(512), nullable=False),
    Column("risk_class", String(32), nullable=False),
    Column("status", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("payload_ref", String(512), nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("expires_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "action_ref", name="pk_action_proposal"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_action_proposal_tenant_run"),
    _fk(
        ["tenant_id", "step_id", "run_id"],
        ["step.tenant_id", "step.step_id", "step.run_id"],
        name="fk_action_proposal_tenant_step_run",
    ),
    _fk(
        [
            "tenant_id",
            "attempt_id",
            "execution_unit_id",
            "source_generation",
            "run_id",
        ],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.execution_unit_id",
            "attempt.generation",
            "attempt.run_id",
        ],
        name="fk_action_proposal_tenant_attempt_unit_generation",
    ),
    UniqueConstraint("tenant_id", "action_ref", "request_digest", name="uq_action_proposal_tenant_action_digest"),
    UniqueConstraint(
        "tenant_id",
        "action_ref",
        "request_digest",
        "run_id",
        name="uq_action_proposal_tenant_action_digest_run",
    ),
    _enum_check("action_proposal", "status", [item.value for item in ActionProposalState]),
    _version_check("action_proposal"),
)

approval_request_table = Table(
    "approval_request",
    metadata,
    _tenant(),
    Column("approval_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("step_id", ID),
    Column("action_ref", ID, nullable=False),
    Column("approval_type", String(64), nullable=False),
    Column("request_digest", String(128), nullable=False),
    Column("status", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("canonical_request_ref", String(512), nullable=False),
    Column("expires_at", TIMESTAMP, nullable=False),
    Column("decided_by", ID),
    Column("decided_at", TIMESTAMP),
    Column("decision_reason", Text),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "approval_id", name="pk_approval_request"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_approval_request_tenant_run"),
    _fk(
        ["tenant_id", "step_id", "run_id"],
        ["step.tenant_id", "step.step_id", "step.run_id"],
        name="fk_approval_request_tenant_step_run",
    ),
    _fk(
        ["tenant_id", "action_ref", "request_digest"],
        ["action_proposal.tenant_id", "action_proposal.action_ref", "action_proposal.request_digest"],
        name="fk_approval_request_tenant_action_digest",
    ),
    _fk(
        ["tenant_id", "action_ref", "request_digest", "run_id"],
        [
            "action_proposal.tenant_id",
            "action_proposal.action_ref",
            "action_proposal.request_digest",
            "action_proposal.run_id",
        ],
        name="fk_approval_request_tenant_action_digest_run",
    ),
    UniqueConstraint("tenant_id", "approval_id", "request_digest", name="uq_approval_request_tenant_approval_digest"),
    UniqueConstraint(
        "tenant_id",
        "approval_id",
        "action_ref",
        "request_digest",
        name="uq_approval_request_tenant_approval_action_digest",
    ),
    UniqueConstraint("tenant_id", "approval_id", "run_id", name="uq_approval_request_tenant_approval_run"),
    _enum_check("approval_request", "status", [item.value for item in ApprovalState]),
    _version_check("approval_request"),
    CheckConstraint(
        "(status = 'PENDING' AND decided_by IS NULL AND decided_at IS NULL) OR "
        "(status <> 'PENDING' AND decided_by IS NOT NULL AND decided_at IS NOT NULL)",
        name="ck_approval_request_decision_shape",
    ),
)

effect_ledger_table = Table(
    "effect_ledger",
    metadata,
    _tenant(),
    Column("effect_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("action_ref", ID, nullable=False),
    Column("approval_id", ID, nullable=False),
    Column("effect_key", String(255), nullable=False),
    Column("request_digest", String(128), nullable=False),
    Column("tool_name", String(255), nullable=False),
    Column("tool_version", String(64), nullable=False),
    Column("tool_spec_digest", String(128), nullable=False),
    Column("connector_name", String(255), nullable=False),
    Column("required_scopes", JSON_DOCUMENT, nullable=False),
    Column("canonical_target", String(512), nullable=False),
    Column("canonical_payload_digest", String(128), nullable=False),
    Column("state", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("executor_id", ID),
    Column("execution_epoch", BigInteger, nullable=False),
    Column("executor_lease_expires_at", TIMESTAMP),
    Column("result_ref", String(512)),
    Column("remote_operation_id", String(255)),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    Column("completed_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "effect_id", name="pk_effect_ledger"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_effect_ledger_tenant_run"),
    _fk(
        ["tenant_id", "action_ref"],
        ["action_proposal.tenant_id", "action_proposal.action_ref"],
        name="fk_effect_ledger_tenant_action",
    ),
    _fk(
        ["tenant_id", "approval_id", "request_digest"],
        ["approval_request.tenant_id", "approval_request.approval_id", "approval_request.request_digest"],
        name="fk_effect_ledger_tenant_approval_digest",
    ),
    _fk(
        ["tenant_id", "approval_id", "action_ref", "request_digest"],
        [
            "approval_request.tenant_id",
            "approval_request.approval_id",
            "approval_request.action_ref",
            "approval_request.request_digest",
        ],
        name="fk_effect_ledger_tenant_approval_action_digest",
    ),
    _fk(
        ["tenant_id", "approval_id", "run_id"],
        ["approval_request.tenant_id", "approval_request.approval_id", "approval_request.run_id"],
        name="fk_effect_ledger_tenant_approval_run",
    ),
    UniqueConstraint("tenant_id", "effect_key", name="uq_effect_ledger_tenant_effect_key"),
    UniqueConstraint(
        "tenant_id",
        "effect_id",
        "run_id",
        name="uq_effect_ledger_tenant_effect_run",
    ),
    _enum_check("effect_ledger", "state", [item.value for item in EffectState]),
    _version_check("effect_ledger"),
    CheckConstraint(
        "(state IN ('SUCCEEDED', 'FAILED') AND completed_at IS NOT NULL) OR "
        "(state NOT IN ('SUCCEEDED', 'FAILED') AND completed_at IS NULL)",
        name="ck_effect_ledger_completion_shape",
    ),
    CheckConstraint(
        "state <> 'PREPARED' OR "
        "(version = 1 AND result_ref IS NULL AND remote_operation_id IS NULL)",
        name="ck_effect_ledger_prepared_shape",
    ),
    CheckConstraint(
        "(state = 'PREPARED' AND executor_id IS NULL AND execution_epoch = 0 "
        "AND executor_lease_expires_at IS NULL) OR "
        "(state = 'EXECUTING' AND executor_id IS NOT NULL AND execution_epoch >= 1 "
        "AND executor_lease_expires_at IS NOT NULL) OR "
        "(state IN ('UNKNOWN', 'SUCCEEDED', 'FAILED') AND executor_id IS NOT NULL "
        "AND execution_epoch >= 1 AND executor_lease_expires_at IS NULL)",
        name="ck_effect_ledger_executor_shape",
    ),
)

ui_surface_table = Table(
    "ui_surface",
    metadata,
    _tenant(),
    Column("surface_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("catalog_id", String(128), nullable=False),
    Column("protocol_version", String(64), nullable=False),
    Column("current_revision", Integer),
    Column("status", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "surface_id", name="pk_ui_surface"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_ui_surface_tenant_run"),
    _fk(
        ["tenant_id", "surface_id", "current_revision"],
        ["ui_surface_revision.tenant_id", "ui_surface_revision.surface_id", "ui_surface_revision.revision"],
        name="fk_ui_surface_tenant_current_revision",
        use_alter=True,
    ),
    _enum_check("ui_surface", "status", ["ACTIVE", "SUPERSEDED", "ARCHIVED"]),
    _version_check("ui_surface"),
    UniqueConstraint("tenant_id", "surface_id", "run_id", name="uq_ui_surface_tenant_surface_run"),
)

ui_surface_revision_table = Table(
    "ui_surface_revision",
    metadata,
    _tenant(),
    Column("surface_id", ID, nullable=False),
    Column("revision", Integer, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("source_attempt_id", ID, nullable=False),
    Column("source_generation", BigInteger, nullable=False),
    Column("source_event_seq", BigInteger, nullable=False),
    Column("document", JSON_DOCUMENT, nullable=False),
    Column("checksum", String(128), nullable=False),
    Column("validation_result", JSON_DOCUMENT, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "surface_id", "revision", name="pk_ui_surface_revision"),
    _fk(
        ["tenant_id", "surface_id", "run_id"],
        ["ui_surface.tenant_id", "ui_surface.surface_id", "ui_surface.run_id"],
        name="fk_ui_surface_revision_tenant_surface_run",
    ),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_ui_surface_revision_tenant_run"),
    _fk(
        ["tenant_id", "source_attempt_id", "source_generation", "run_id"],
        [
            "attempt.tenant_id",
            "attempt.attempt_id",
            "attempt.generation",
            "attempt.run_id",
        ],
        name="fk_ui_surface_revision_tenant_attempt_fence_run",
    ),
    _fk(
        ["tenant_id", "run_id", "source_event_seq"],
        ["run_event.tenant_id", "run_event.run_id", "run_event.event_seq"],
        name="fk_ui_surface_revision_tenant_run_event_seq",
        use_alter=True,
    ),
    UniqueConstraint(
        "tenant_id",
        "run_id",
        "source_event_seq",
        "surface_id",
        name="uq_ui_surface_revision_tenant_run_event_surface",
    ),
    CheckConstraint("revision >= 1", name="ck_ui_surface_revision_revision"),
    CheckConstraint("source_generation >= 1", name="ck_ui_surface_revision_source_generation"),
)

run_event_table = Table(
    "run_event",
    metadata,
    _tenant(),
    Column("event_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("event_seq", BigInteger, nullable=False),
    Column("schema_version", String(64), nullable=False),
    Column("event_type", String(128), nullable=False),
    Column("occurred_at", TIMESTAMP, nullable=False),
    Column("producer_service", String(128), nullable=False),
    Column("payload_schema", String(128), nullable=False),
    Column("payload", JSON_DOCUMENT, nullable=False),
    Column("attempt_id", ID),
    Column("causation_event_id", ID),
    Column("trace_id", String(128)),
    PrimaryKeyConstraint("tenant_id", "event_id", name="pk_run_event"),
    _fk(
        ["tenant_id", "attempt_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.run_id"],
        name="fk_run_event_tenant_attempt_run",
        use_alter=True,
    ),
    UniqueConstraint("tenant_id", "run_id", "event_seq", name="uq_run_event_tenant_run_seq"),
    UniqueConstraint("tenant_id", "event_id", "run_id", name="uq_run_event_tenant_event_run"),
    CheckConstraint("event_seq >= 1", name="ck_run_event_event_seq"),
    Index("ix_run_event_tenant_run_seq", "tenant_id", "run_id", "event_seq"),
)

audit_event_table = Table(
    "audit_event",
    metadata,
    _tenant(),
    Column("audit_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("actor_id", ID, nullable=False),
    Column("initiating_actor", ID, nullable=False),
    Column("effective_actor", ID),
    Column("on_behalf_of", ID),
    Column("action", String(128), nullable=False),
    Column("entity_type", String(64), nullable=False),
    Column("entity_id", ID, nullable=False),
    Column("entity_version", Integer, nullable=False),
    Column("before_version", Integer),
    Column("after_version", Integer),
    Column("outcome", String(64), nullable=False),
    Column("policy_version", String(64)),
    Column("policy_decision", String(64)),
    Column("grant_id", ID),
    Column("approval_id", ID),
    Column("effect_id", ID),
    Column("request_digest", String(128)),
    Column("lease_generation", BigInteger),
    Column("trace_id", String(128)),
    Column("failure_code", String(128)),
    Column("detail", JSON_DOCUMENT, nullable=False),
    Column("occurred_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "audit_id", name="pk_audit_event"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_audit_event_tenant_run"),
    _fk(
        ["tenant_id", "grant_id", "run_id"],
        ["tool_grant.tenant_id", "tool_grant.grant_id", "tool_grant.run_id"],
        name="fk_audit_event_tenant_grant_run",
    ),
    _fk(
        ["tenant_id", "approval_id", "run_id"],
        ["approval_request.tenant_id", "approval_request.approval_id", "approval_request.run_id"],
        name="fk_audit_event_tenant_approval_run",
    ),
    _fk(
        ["tenant_id", "effect_id", "run_id"],
        ["effect_ledger.tenant_id", "effect_ledger.effect_id", "effect_ledger.run_id"],
        name="fk_audit_event_tenant_effect_run",
    ),
    CheckConstraint("entity_version >= 1", name="ck_audit_event_entity_version"),
    CheckConstraint(
        "lease_generation IS NULL OR lease_generation >= 1",
        name="ck_audit_event_lease_generation",
    ),
    Index("ix_audit_event_tenant_run_occurred", "tenant_id", "run_id", "occurred_at"),
)

outbox_message_table = Table(
    "outbox_message",
    metadata,
    _tenant(),
    Column("message_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("aggregate_type", String(64), nullable=False),
    Column("aggregate_id", ID, nullable=False),
    Column("aggregate_version", Integer, nullable=False),
    Column("topic", String(255), nullable=False),
    Column("schema_version", String(64), nullable=False),
    Column("payload_schema", String(64), nullable=False),
    Column("payload", JSON_DOCUMENT, nullable=False),
    Column("publish_state", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("event_id", ID),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("published_at", TIMESTAMP),
    Column("delivery_attempts", Integer, nullable=False),
    Column("next_attempt_at", TIMESTAMP),
    Column("last_error", String(512)),
    Column("last_error_code", String(128)),
    PrimaryKeyConstraint("tenant_id", "message_id", name="pk_outbox_message"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_outbox_message_tenant_run"),
    _fk(
        ["tenant_id", "event_id", "run_id"],
        ["run_event.tenant_id", "run_event.event_id", "run_event.run_id"],
        name="fk_outbox_message_tenant_event_run",
    ),
    UniqueConstraint(
        "tenant_id",
        "aggregate_type",
        "aggregate_id",
        "aggregate_version",
        "topic",
        name="uq_outbox_message_tenant_aggregate_version_topic",
    ),
    CheckConstraint("delivery_attempts >= 0", name="ck_outbox_message_delivery_attempts"),
    _enum_check("outbox_message", "publish_state", ["PENDING", "PUBLISHED", "FAILED"]),
    _version_check("outbox_message"),
    CheckConstraint(
        "publish_state <> 'PUBLISHED' OR published_at IS NOT NULL",
        name="ck_outbox_message_published_shape",
    ),
    CheckConstraint(
        "version <> 1 OR (publish_state = 'PENDING' AND delivery_attempts = 0 "
        "AND published_at IS NULL AND next_attempt_at IS NULL "
        "AND last_error IS NULL AND last_error_code IS NULL)",
        name="ck_outbox_message_initial_shape",
    ),
    Index(
        "ix_outbox_message_tenant_publish_next_created",
        "tenant_id",
        "publish_state",
        "next_attempt_at",
        "created_at",
    ),
)

inbox_message_table = Table(
    "inbox_message",
    metadata,
    _tenant(),
    Column("message_id", ID, nullable=False),
    Column("handler_version", String(64), nullable=False),
    Column("topic", String(255), nullable=False),
    Column("payload_schema", String(64), nullable=False),
    Column("payload_digest", String(128), nullable=False),
    Column("processing_state", STATE, nullable=False),
    Column("version", Integer, nullable=False),
    Column("received_at", TIMESTAMP, nullable=False),
    Column("processed_at", TIMESTAMP),
    Column("failure_code", String(128)),
    PrimaryKeyConstraint("tenant_id", "message_id", "handler_version", name="pk_inbox_message"),
    _enum_check("inbox_message", "processing_state", ["RECEIVED", "PROCESSED", "FAILED"]),
    _version_check("inbox_message"),
    Index("ix_inbox_message_tenant_state_received", "tenant_id", "processing_state", "received_at"),
)

cost_ledger_table = Table(
    "cost_ledger",
    metadata,
    _tenant(),
    Column("entry_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("attempt_id", ID),
    Column("category", String(64), nullable=False),
    Column("dimension", String(64), nullable=False),
    Column("quantity", Numeric(38, 12), nullable=False),
    Column("unit", String(32), nullable=False),
    Column("model_class", String(128)),
    Column("runtime_class", String(128)),
    Column("tool_class", String(128)),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("occurred_at", TIMESTAMP, nullable=False),
    PrimaryKeyConstraint("tenant_id", "entry_id", name="pk_cost_ledger"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_cost_ledger_tenant_run"),
    _fk(
        ["tenant_id", "attempt_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.run_id"],
        name="fk_cost_ledger_tenant_attempt_run",
    ),
    CheckConstraint("quantity >= 0", name="ck_cost_ledger_quantity"),
)

execution_error_table = Table(
    "execution_error",
    metadata,
    _tenant(),
    Column("error_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("attempt_id", ID),
    Column("phase", String(64), nullable=False),
    Column("category", String(64), nullable=False),
    Column("code", String(128), nullable=False),
    Column("sanitized_message", String(512), nullable=False),
    Column("detail_ref", String(512)),
    Column("restricted_detail_ref", String(512)),
    Column("retry_disposition", String(64), nullable=False),
    Column("fingerprint", String(128), nullable=False),
    Column("trace_id", String(128)),
    Column("schema_version", String(64), nullable=False),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("resolved_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "error_id", name="pk_execution_error"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_execution_error_tenant_run"),
    _fk(
        ["tenant_id", "attempt_id", "run_id"],
        ["attempt.tenant_id", "attempt.attempt_id", "attempt.run_id"],
        name="fk_execution_error_tenant_attempt_run",
    ),
    _version_check("execution_error"),
)

followup_request_table = Table(
    "followup_request",
    metadata,
    _tenant(),
    Column("followup_id", ID, nullable=False),
    Column("run_id", ID, nullable=False),
    Column("question", Text, nullable=False),
    Column("client_followup_id", String(255), nullable=False),
    Column("status", STATE, nullable=False),
    Column("answer", Text),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("answered_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "followup_id", name="pk_followup_request"),
    _fk(["tenant_id", "run_id"], ["run.tenant_id", "run.run_id"], name="fk_followup_request_tenant_run"),
    _enum_check("followup_request", "status", ["PENDING", "ANSWERED"]),
    _version_check("followup_request"),
)

idempotency_record_table = Table(
    "idempotency_record",
    metadata,
    _tenant(),
    Column("command_type", String(128), nullable=False),
    Column("idempotency_key", String(255), nullable=False),
    Column("actor_id", ID, nullable=False),
    Column("request_digest", String(128), nullable=False),
    Column("state", STATE, nullable=False),
    Column("result_type", String(64)),
    Column("result_schema", String(64)),
    Column("result_ref", ID),
    Column("result_payload", JSON_DOCUMENT),
    Column("version", Integer, nullable=False),
    Column("created_at", TIMESTAMP, nullable=False),
    Column("updated_at", TIMESTAMP, nullable=False),
    # TTL horizon: a key may be recycled after expiry and expired rows are
    # purgeable (SDD §13.2 — IdempotencyRecord no longer accumulates forever).
    Column("expires_at", TIMESTAMP),
    PrimaryKeyConstraint("tenant_id", "command_type", "idempotency_key", name="pk_idempotency_record"),
    _enum_check("idempotency_record", "state", ["IN_PROGRESS", "COMPLETED"]),
    _version_check("idempotency_record"),
    CheckConstraint(
        "(state = 'IN_PROGRESS' AND result_type IS NULL AND result_schema IS NULL "
        "AND result_ref IS NULL AND result_payload IS NULL) OR "
        "(state = 'COMPLETED' AND result_type IS NOT NULL AND result_schema IS NOT NULL)",
        name="ck_idempotency_record_result_shape",
    ),
)


__all__ = [
    "action_proposal_table",
    "approval_request_table",
    "artifact_table",
    "artifact_version_table",
    "attempt_step_table",
    "attempt_table",
    "audit_event_table",
    "checkpoint_table",
    "cost_ledger_table",
    "effect_ledger_table",
    "execution_error_table",
    "execution_lease_table",
    "execution_unit_table",
    "followup_request_table",
    "idempotency_record_table",
    "inbox_message_table",
    "metadata",
    "outbox_message_table",
    "run_authorization_snapshot_table",
    "run_event_table",
    "run_table",
    "step_table",
    "tool_grant_table",
    "tool_invocation_table",
    "ui_surface_revision_table",
    "ui_surface_table",
    "workspace_snapshot_table",
]
